### ISSUE TITLE
waf failed to run under Msys2

### ISSUE THREAD

**Issue by AnClark** [mruby-zest/mruby-zest-build#31]
Now I'm trying to build Zest under Msys2, but PUGL's `waf` failed to run, no matter which Python I'm using (MSYS Python 3, or MinGW-w64's native Python 2/3).

On native Python within MinGW-w64 environment:

```bash
# Assume that I'm in mruby-zest-build/deps/pugl

# This is Python 2.7.18
$ python2 ./waf
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/logging/__init__.py", line 879, in emit
    stream.write(ufs % msg)
  File "C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/waf-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Logs.py", line 26, in write
    self.stream.write(txt)
LookupError: unknown encoding: cp65001
Logged from file Logs.py, line 131

# And this is Python 3.8
$ python ./waf
No wscript file in directory C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl
```

On MSYS Python 3:

```bash
$ /usr/bin/python ./waf --help
Traceback (most recent call last):
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Node.py", line 282, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Scripting.py", line 149, in run_commands
    parse_options()
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Scripting.py", line 127, in parse_options
    Context.create_context('options').execute()
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Options.py", line 134, in execute
    super(OptionsContext,self).execute()
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Context.py", line 84, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Context.py", line 125, in recurse
    user_function(self)
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/wscript", line 24, in options
    opt.load('compiler_c')
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Context.py", line 81, in load
    fun(self)
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Tools/compiler_c.py", line 31, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Context.py", line 261, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Node.py", line 331, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/c/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/deps/pugl/.waf3-1.7.14-1d85101ae0766bdefb229332e6c04d3b/waflib/Node.py", line 331, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

But **everything is OK under Arch Linux or WSL Ubuntu**. I don't know **if `waf` is incompatible with Msys2 or not**.

**Comment by fundamental** [comment]
The easiest thing to do is to just bypass waf completely. PUGL has the unfortunate issue of having forks, incompatible versions, etc. We've been using an old version and as such the waf stuff has bit-rot pretty well.

See https://github.com/mruby-zest/mruby-zest-build/commit/af6563d32ac32e5cb7b9821b066edeec5a135290 for how we could sidestep it for Linux builds. Sanity checking windows takes a few more steps for me, but it should basically be the same change for the windows build target (pugl_win.c instead of pugl_x11.c IIRC). Let me know if that bypass works on your system and I'll commit it.

**Comment by AnClark** [comment]
Thanks a lot! I'll give it a try.

**Comment by AnClark** [comment]
@fundamental But when compiling MRuby within Msys2, there's a linker error. 
I'm new to both Ruby and Rake.

```bash
INSTALL build/host/bin/mrbc.exe -> bin/mrbc.exe
INSTALL build/host/bin/mruby-config.bat -> bin/mruby-config.bat
CC    mrbgems/mruby-bin-mirb/tools/mirb/mirb.c -> build/host/mrbgems/mruby-bin-mirb/tools/mirb/mirb.o
LD    build/host/bin/mirb.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x23e): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2b5): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x319): undefined reference to `__imp_getaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x385): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x77b): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x7be): undefined reference to `__imp_getaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x7d3): undefined reference to `gai_strerrorA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x91a): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xb2e): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xb43): undefined reference to `gai_strerrorA'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xcf5): undefined reference to `__imp_ntohs'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xd78): undefined reference to `__imp_getnameinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xee9): undefined reference to `__imp_getsockname'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0xf7e): undefined reference to `__imp_getpeername'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1000): undefined reference to `__imp_getsockname'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x10b5): undefined reference to `__imp_getsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x124c): undefined reference to `__imp_recv'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x13b0): undefined reference to `__imp_recvfrom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1554): undefined reference to `__imp_send'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x169c): undefined reference to `__imp_sendto'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1730): undefined reference to `__imp_ioctlsocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1aef): undefined reference to `__imp_setsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1b73): undefined reference to `__imp_shutdown'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x1f45): undefined reference to `__imp_recvfrom'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2081): undefined reference to `__imp_gethostname'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x213b): undefined reference to `__imp_accept'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x21ff): undefined reference to `__imp_accept'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2353): undefined reference to `__imp_bind'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2440): undefined reference to `__imp_connect'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x24a7): undefined reference to `__imp_listen'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2675): undefined reference to `__imp_socket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x272f): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x28a9): undefined reference to `__imp_recv'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2a98): undefined reference to `__imp_send'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x2af5): undefined reference to `__imp_WSAStartup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x422b): undefined reference to `__imp_freeaddrinfo'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(socket.o):socket.c:(.text+0x4234): undefined reference to `__imp_WSACleanup'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x109c): undefined reference to `__imp_getsockopt'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x1340): undefined reference to `__imp_closesocket'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x134d): undefined reference to `__imp_WSAGetLastError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2834): undefined reference to `__imp_select'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2a56): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2a74): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2c3a): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2cdd): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2ea3): undefined reference to `__WSAFDIsSet'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Sources/zyn-fusion-build/tmp/src_git/mruby-zest-build/mruby/build/host/lib/libmruby.a(io.o):io.c:(.text+0x2f46): more undefined references to `__WSAFDIsSet' follow
collect2.exe: error: ld returned 1 exit status
```

Notes:
- I have libuv built under `mruby-zest-build/deps/libuv-win.a`, which is properly built by `make builddepwin`.

**Comment by fundamental** [comment]
This looks unrelated to libuv or any of the zest code (I think). The errors appear to be coming from mruby-socket which is not part of the build for the target library, but does appear to be part of the compile for mruby tools needed to bootstrap. I'd wager the check at mruby/mrbgems/mruby-socket/mrbgem.rake:10 is getting set incorrectly and not linking to those libs. 

Since the bootstrapping tooling when cross compiling does not need sockets, it's something that we could likely bypass by modifying our build_config.rb:23 to a more conservative listing of gems, though that likely involves some trial and error.

I don't have a msys2 setup to validate changes with, though I should be able to spin up a mingw docker container with my next hacking session.

**Comment by AnClark** [comment]
Yes, maybe bypassing the `mruby-socket` module is a good choice.

**Comment by fundamental** [comment]
mruby-io also has the same "for_windows?" check. Perhaps one of the older bugs has been resolved, but for ages either I was able to get that check to work correctly xor the check needed in the regular expression library. This was part of the old patch sets applied to mruby and other hackery. Let's see if that gem has updates pending as well...

**Comment by fundamental** [comment]
Nope, that gem (mruby-regex-pcre) still uses if /mingw|mswin/ =~ RUBY_PLATFORM . Last time I went looking (and I lost a good few hours searching) the conventions around the cross-compilation scenario were not clearly discussed.

**Comment by AnClark** [comment]
I found another solution by applying these following changes:

### 1. Keep `mruby-io` and `mruby-socket` as-is
### 2. Bypass `mruby-socket`, and any CLIs except `mrbc`,  by creating a custom gembox  `zest` located in `mruby/mrbgems/zest.gembox`.

```ruby
MRuby::GemBox.new do |conf|
  conf.gembox "stdlib"
  conf.gembox "stdlib-ext"
  conf.gembox "math"
  conf.gembox "metaprog"

  # Use stdlib-io except mruby-socket
  conf.gem :core => "mruby-io"
  conf.gem :core => "mruby-print"

  # Generate mrbc command
  conf.gem :core => "mruby-bin-mrbc"

end
```

### 3. Modify `build_config.rb` correspondingly:

```diff
diff --git a/build_config.rb b/build_config.rb
index d71a39e..b1071ee 100644
--- a/build_config.rb
+++ b/build_config.rb
@@ -20,7 +20,7 @@ if(windows)
     conf.archiver do |archiver|
       archiver.command = 'ar'
     end
-    conf.gembox 'default'
+    conf.gembox 'zest'
   end
 end

@@ -147,12 +147,20 @@ MRuby::Build.new('host-debug') do |conf|

   enable_debug

-  # include the default GEMs
-  conf.gembox 'default'
+  if(windows)
+    # include GEMs without CLIs
+    conf.gembox 'zest'
+  else
+    # include default GEMs
+    conf.gembox 'default'
+  end

   # C compiler settings
   conf.cc.defines = %w(MRB_ENABLE_DEBUG_HOOK MRUBY_NANOVG_GL2)

   # Generate mruby debugger command (require mruby-eval)
-  conf.gem :core => "mruby-bin-debugger"
+  # Do not build it under Windows, or linker error will occur
+  if(!windows)
+    conf.gem :core => "mruby-bin-debugger"
+  end
 end
```

### 4. Patch `mruby/src/backtrace.c` (I'm not sure whether it works or not)
Use this patch to replace the corresponding part in `zyn-fusion-build/mruby-float-patch.patch`.

```diff
diff --git a/src/backtrace.c b/src/backtrace.c
index 1006f2f8..bf58aa3e 100644
--- a/src/backtrace.c
+++ b/src/backtrace.c
@@ -76,13 +76,16 @@ each_backtrace(mrb_state *mrb, ptrdiff_t ciidx, const mrb_code *pc0, each_backtr

 #ifndef MRB_NO_STDIO

+char superhack[1024*20];
+
 static void
 print_backtrace(mrb_state *mrb, struct RObject *exc, mrb_value backtrace)
 {
   mrb_int i;
   mrb_int n = RARRAY_LEN(backtrace);
   mrb_value *loc, mesg;
-  FILE *stream = stderr;
+  // FILE *stream = stderr;
+  char stream[1000];

   if (n != 0) {
     fprintf(stream, "trace (most recent call last):\n");
@@ -92,9 +95,11 @@ print_backtrace(mrb_state *mrb, struct RObject *exc, mrb_value backtrace)
                 (int)i, (int)RSTRING_LEN(*loc), RSTRING_PTR(*loc));
       }
     }
-    if (mrb_string_p(*loc)) {
-      fprintf(stream, "%.*s: ", (int)RSTRING_LEN(*loc), RSTRING_PTR(*loc));
-    }
+    //if (mrb_string_p(*loc)) {
+    //  fprintf(stream, "%.*s: ", (int)RSTRING_LEN(*loc), RSTRING_PTR(*loc));
+    //}
+    sprintf(stream, "\t[%d] %.*s\n", i, (int)RSTRING_LEN(*loc), RSTRING_PTR(*loc));
+    strcat(superhack, stream);
   }
   mesg = mrb_exc_inspect(mrb, mrb_obj_value(exc));
   fprintf(stream, "%.*s\n", (int)RSTRING_LEN(mesg), RSTRING_PTR(mesg));
```
